# adapa is a collection of services for orchestration of distributed systems
# this playbook will install the core components, supervisor, etcd, and serf

- name: setting up adapa services
  hosts: one:two

  pre_tasks:
    - name: creating directories for basic setup
      file: path={{ item }} state=directory
      with_items:
        - ~/bin
        - ~/tmp

  roles:
    - supervisord
    - etcd
    - serf

